server:
  port: 10002
  servlet:
    context-path: /
spring:
  security:
    user:
      name: wanli
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
    database: 5
    password: redis123
mybatis-plus:
  mapper-locations: classpath*:mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.wanli.entity
logging:
  level:
    org.springframework: info
token:
  jwt:
    secret: admin
    expire: 604800
    header: TOKEN
# 配置oss
aliyun:
  accessKeyId: LTAI5tJH8fk5cqTeX9vTLAD3
  secretAccessKey: oLRPRBi8PXqmaj4EcwdTno85bKaSwB
  oss:
    endPoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: wanli-system

